### ISSUE TITLE
Ascii85.prototype.decode method should return Buffer object instead of string

### ISSUE THREAD

**Issue by J-F-Liu** [huandu/node-ascii85#1]

**Comment by huandu** [comment]
Sounds reasonable. I can implement it in this week.

**Comment by J-F-Liu** [comment]
Thanks, I'm using your package is this web app: http://canvasgames.net/tool/coder.html

**Comment by J-F-Liu** [comment]
But encode method should still accept Buffer and return string.

**Comment by huandu** [comment]
If you need an encoded string, just do `buf.toString()`.
