### ISSUE TITLE
Decoded result is not correct when using ascii85.ZeroMQ

### ISSUE THREAD

**Issue by J-F-Liu** [huandu/node-ascii85#3]
Can be tested on this page: http://canvasgames.net/tool/coder.html
![image](https://cloud.githubusercontent.com/assets/1472963/20133309/08f43cae-a6a2-11e6-94f3-a16bbd6c0867.png)

**Comment by huandu** [comment]
Thanks for raising this issue. I will investigate and fix it soon.
